# Generated by Django 3.2.25 on 2024-10-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('conform_password', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
